# frozen_string_literal: true

module Skills
  Config = Data.define(:root, :ignore, :targets, :project_roots, :allowlist_path) do
    Target = Data.define(:name, :path)

    def self.load(root)
      root = Pathname(root).expand_path
      data = TomlRB.load_file(root.join("tooling/skills/skills.toml"))
      targets = Array(data.fetch("target", [])).map do |target|
        Target.new(target.fetch("name"), expand(target.fetch("path")))
      end
      project_roots = Array(data.fetch("project_roots", [])).map { |path| expand(path) }
      new(root, Set.new(data.fetch("ignore", [])), targets, project_roots, root.join("allowlist.txt"))
    end

    def self.expand(path)
      Pathname(path.sub(%r{\A~(?=/|\z)}, Dir.home)).expand_path
    end

    def global_manifest
      root.join("global-manifest.toml")
    end

    def manifest_skills(path = global_manifest)
      return [] unless path.file?

      Array(TomlRB.load_file(path).fetch("skills", [])).map(&:to_s).sort
    rescue TomlRB::ParseError => error
      raise ArgumentError, "invalid TOML in #{path}: #{error.message}"
    end

    def project_manifest(project)
      Pathname(project).join(".agents/skills-manifest.toml")
    end

    def project_resolution(project)
      manifest = project_manifest(project)
      data = manifest.file? ? TomlRB.load_file(manifest) : {}
      ((manifest_skills - Array(data.fetch("exclude", []))) | Array(data.fetch("add", []))).map(&:to_s).sort
    rescue TomlRB::ParseError => error
      raise ArgumentError, "invalid TOML in #{manifest}: #{error.message}"
    end

    def write_manifest(path, skills)
      body = [
        "# Generated by skills; edit with `skills enable` or `skills disable`.",
        "skills = ["
      ]
      body.concat(skills.sort.map { |name| "  #{name.inspect}," })
      body << "]"
      File.write(path, "#{body.join("\n")}\n")
    end

    def write_project_manifest(path, add:, exclude:)
      lines = ["# Generated by skills; edit with `skills enable` or `skills disable`."]
      lines << "add = [#{add.sort.map(&:inspect).join(", ")}]"
      lines << "exclude = [#{exclude.sort.map(&:inspect).join(", ")}]"
      FileUtils.mkdir_p(path.dirname)
      File.write(path, "#{lines.join("\n")}\n")
    end

    def allowlist
      return [] unless allowlist_path.file?

      allowlist_path.readlines(chomp: true).map(&:strip).reject { |line| line.empty? || line.start_with?("#") }
    end
  end
end
